# know tensor 

In [51]:
import torch

# 3D tensor

t3 = torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                    [[1,2,3],
                     [4,5,6],
                     [7,8,9]],
                    [[1,2,3],
                     [4,5,6],
                     [7,8,9]]
                    ])

print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [52]:
#tensor operations

import math
a= torch.rand(1,2) * 2 -1
print(a)
print(torch.abs(a))  #abs(a) = |a|
print(torch.ceil(a)) #ceil 주어진 숫자보다 크거나 같은 정수 반환
print(torch.floor(a)) #바닥 함수, 실수 이하의 정수 함수 
print(torch.clamp(a,-0.5,0.5)) #사이에 위치하게 찝어버리는 것, 특정 범위 내로 값 제한

tensor([[0.1022, 0.1794]])
tensor([[0.1022, 0.1794]])
tensor([[1., 1.]])
tensor([[0., 0.]])
tensor([[0.1022, 0.1794]])


In [31]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,2])))

tensor([[-0.1746,  0.3640]])
tensor(-0.1746)
tensor(0.3640)
tensor(0.0947)
tensor(0.3809)
tensor(-0.0636)
tensor([1, 2, 3])


In [ ]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0)) #열끼리 값 비교
print(x.max(dim=1)) #행끼리    
#indices=tensor([1, 1]))

#indices=tensor([0, 0]))!! 왜 이렇게 나오는지모름!!

tensor([[0.2419, 0.0226],
        [0.6413, 0.5880]])
torch.return_types.max(
values=tensor([0.6413, 0.5880]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([0.2419, 0.6413]),
indices=tensor([0, 0]))


In [34]:
x = torch.rand(2,2)
print(x)
print(x.min(dim=0)) #열끼리 값 비교
print(x.min(dim=1)) #행끼리    

tensor([[0.1067, 0.2854],
        [0.2043, 0.1122]])
torch.return_types.min(
values=tensor([0.1067, 0.1122]),
indices=tensor([0, 1]))
torch.return_types.min(
values=tensor([0.1067, 0.1122]),
indices=tensor([0, 1]))


In [35]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)
y.add_(x) #x+y 를 y에 inplace

tensor([[0.6512, 0.9018],
        [0.7267, 0.1926]])
tensor([[0.2201, 0.2385],
        [0.3471, 0.5388]])


tensor([[0.8714, 1.1403],
        [1.0738, 0.7314]])

In [ ]:
#view 

x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)

z= x.view(5,-1)   # -1은  크키값 유추
print(z)

tensor([[-0.3643, -0.3240, -0.3973, -0.5261, -0.6739],
        [-1.4791,  0.9978, -0.1019, -0.7801, -0.0655],
        [ 0.4608, -0.2796,  0.0259, -1.2670, -1.3541],
        [ 0.8877,  0.2201,  0.2237,  0.4378,  1.5079]])
tensor([-0.3643, -0.3240, -0.3973, -0.5261, -0.6739, -1.4791,  0.9978, -0.1019,
        -0.7801, -0.0655,  0.4608, -0.2796,  0.0259, -1.2670, -1.3541,  0.8877,
         0.2201,  0.2237,  0.4378,  1.5079])
tensor([[-0.3643, -0.3240, -0.3973, -0.5261],
        [-0.6739, -1.4791,  0.9978, -0.1019],
        [-0.7801, -0.0655,  0.4608, -0.2796],
        [ 0.0259, -1.2670, -1.3541,  0.8877],
        [ 0.2201,  0.2237,  0.4378,  1.5079]])


In [40]:
x= torch.randn(1)
print(x.item())

0.9882844686508179


In [ ]:
 #squeeze 1크기기 차원 제거
 
x = torch.randn(1,3,3)
print(x)
print(x.shape)
x.squeeze_()
print(x)
print(x.shape)

tensor([[[-0.8346, -0.8747,  0.5545],
         [ 0.8653,  0.0762,  0.0961],
         [-1.4589, -0.0674, -0.8211]]])
torch.Size([1, 3, 3])
tensor([[-0.8346, -0.8747,  0.5545],
        [ 0.8653,  0.0762,  0.0961],
        [-1.4589, -0.0674, -0.8211]])
torch.Size([3, 3])


In [45]:
#unsqueeze 차원을 증가()

tensor = x.unsqueeze(dim = 0)
print(tensor)
print(tensor.shape) 

tensor([[[-0.8346, -0.8747,  0.5545],
         [ 0.8653,  0.0762,  0.0961],
         [-1.4589, -0.0674, -0.8211]]])
torch.Size([1, 3, 3])


In [46]:
tensor = x.unsqueeze(dim = 2)
print(tensor)
print(tensor.shape) 

tensor([[[-0.8346],
         [-0.8747],
         [ 0.5545]],

        [[ 0.8653],
         [ 0.0762],
         [ 0.0961]],

        [[-1.4589],
         [-0.0674],
         [-0.8211]]])
torch.Size([3, 3, 1])


In [47]:
#concatenate
a = torch.randn(1,3,3)
print(a)
b = torch.randn(1,3,3)
print(b)

c = torch.cat((a,b), dim =0)
print(c)
print(c.shape)

tensor([[[ 0.8289, -0.0801, -0.9944],
         [-1.0942,  2.1836, -0.6330],
         [ 0.4873, -0.0540, -0.3368]]])
tensor([[[-0.0573,  1.2158, -1.7329],
         [ 1.5686, -0.5916,  0.0516],
         [-0.2844, -0.5247,  0.1357]]])
tensor([[[ 0.8289, -0.0801, -0.9944],
         [-1.0942,  2.1836, -0.6330],
         [ 0.4873, -0.0540, -0.3368]],

        [[-0.0573,  1.2158, -1.7329],
         [ 1.5686, -0.5916,  0.0516],
         [-0.2844, -0.5247,  0.1357]]])
torch.Size([2, 3, 3])


In [48]:
c = torch.cat((a,b), dim =1)
print(c)
print(c.shape)

tensor([[[ 0.8289, -0.0801, -0.9944],
         [-1.0942,  2.1836, -0.6330],
         [ 0.4873, -0.0540, -0.3368],
         [-0.0573,  1.2158, -1.7329],
         [ 1.5686, -0.5916,  0.0516],
         [-0.2844, -0.5247,  0.1357]]])
torch.Size([1, 6, 3])


In [49]:
#chuck
tensor = torch.rand(3,6)
print(tensor)
t1,t2,t3 = torch.chunk(tensor, 3, dim = 1)
print(t1)
print(t2)
print(t3)

tensor([[0.3453, 0.8211, 0.9385, 0.1323, 0.1515, 0.2260],
        [0.3015, 0.9201, 0.3132, 0.8879, 0.8687, 0.5471],
        [0.1967, 0.3776, 0.5506, 0.5917, 0.7888, 0.8957]])
tensor([[0.3453, 0.8211],
        [0.3015, 0.9201],
        [0.1967, 0.3776]])
tensor([[0.9385, 0.1323],
        [0.3132, 0.8879],
        [0.5506, 0.5917]])
tensor([[0.1515, 0.2260],
        [0.8687, 0.5471],
        [0.7888, 0.8957]])


In [50]:
#split 
t1, t2 = torch.split(tensor, 3, dim = 1)

print(tensor)
print(t1)
print(t2)

tensor([[0.3453, 0.8211, 0.9385, 0.1323, 0.1515, 0.2260],
        [0.3015, 0.9201, 0.3132, 0.8879, 0.8687, 0.5471],
        [0.1967, 0.3776, 0.5506, 0.5917, 0.7888, 0.8957]])
tensor([[0.3453, 0.8211, 0.9385],
        [0.3015, 0.9201, 0.3132],
        [0.1967, 0.3776, 0.5506]])
tensor([[0.1323, 0.1515, 0.2260],
        [0.8879, 0.8687, 0.5471],
        [0.5917, 0.7888, 0.8957]])


## tensor and numpy

In [53]:
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [54]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#memory share(if CPU)
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [57]:
import numpy as np
a = np.ones(7)
b = torch.from_numpy(a)
np.add(a,1,out =a) #output은 a이다
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


### Autograd

In [ ]:
a = torch.randn(3,3)
a= a*3
print(a)
print(a.requires_grad)  #first False

tensor([[-0.6824, -5.4141,  4.5977],
        [-2.9538,  2.9832,  2.6810],
        [ 1.5169, -2.4742, -0.9440]])
False


In [59]:
 a.requires_grad_(True) # inplace a'
 print(a.requires_grad)
 
 b = (a*a).sum()
 print(b)
 print(b.grad_fn)
 

True
tensor(85.0426, grad_fn=<SumBackward0>)


### 기울기

In [61]:
x = torch.ones(3,3, requires_grad = True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [ ]:
y = x+5
print(y) 

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [63]:
z = y*y
out = z.mean()
print(z, out)

tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)


- 계산이 완료된 후, backward() 를 호출 시 자동 역전파 계산 가능, .grad 속성에 누적됨

In [64]:
print(out)
out.backward()

tensor(36., grad_fn=<MeanBackward0>)


In [65]:
# grad : data 가 거쳐온 layer에 대한 미분값 저장

print(x)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [77]:
x = torch.randn(3, requires_grad = True)

y = x*2
while y.data.norm() < 1000:
    y = y*2
    
    print(y)

tensor([-1.4645, -0.1537,  1.1152], grad_fn=<MulBackward0>)
tensor([-2.9290, -0.3073,  2.2303], grad_fn=<MulBackward0>)
tensor([-5.8580, -0.6146,  4.4606], grad_fn=<MulBackward0>)
tensor([-11.7160,  -1.2292,   8.9212], grad_fn=<MulBackward0>)
tensor([-23.4320,  -2.4584,  17.8424], grad_fn=<MulBackward0>)
tensor([-46.8641,  -4.9168,  35.6848], grad_fn=<MulBackward0>)
tensor([-93.7281,  -9.8337,  71.3697], grad_fn=<MulBackward0>)
tensor([-187.4562,  -19.6674,  142.7394], grad_fn=<MulBackward0>)
tensor([-374.9124,  -39.3347,  285.4787], grad_fn=<MulBackward0>)
tensor([-749.8248,  -78.6694,  570.9575], grad_fn=<MulBackward0>)
tensor([-1499.6497,  -157.3388,  1141.9149], grad_fn=<MulBackward0>)


In [78]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)

print(x.grad)

tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])
