In [17]:
import torch 
torch.__version__

'2.7.1+cu126'

In [18]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [19]:
scalar.ndim

0

In [20]:
# 하나의 요소만 가지고 올때
scalar.item()

7

In [21]:
# 텐서 
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
#create a random tensor of size (224,224,3)
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [24]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [25]:
# 이전 텐서와 같은 모양을 가진 다른 텐서

ten_zeros = torch.zeros_like(input = TENSOR)
print(ten_zeros)
 

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])


In [26]:
# Default datatype for tensors is float32

float_32_tensor = torch.tensor([3.0,6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [27]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16)

float_16_tensor.dtype

torch.float16

- 텐서의 정보 알기

- shape- 텐서는 어떤 모양인가요? (일부 연산에는 특정 모양 규칙이 필요함)
- dtype- 텐서 내의 원소는 어떤 데이터 유형으로 저장되어 있나요?
- device- 텐서는 어떤 장치에 저장되나요? (보통 GPU나 CPU)

-  텐서 조작(텐서 연산)
- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [28]:
# add
tensor = torch.tensor([1,2,3])
tensor  + 10

tensor([11, 12, 13])

In [29]:
#  Multiply
tensor  * 10

tensor([10, 20, 30])

In [30]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [31]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [33]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
tensor = torch.tensor([1,2,3])
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [38]:
# add(), multiply() or mul() 등 내장 함수가 있음

# Can also use torch functions
print(torch.mul(tensor, 10))
# Original tensor is still unchanged 
tensor

tensor([10, 20, 30])


tensor([1, 2, 3])

### 행렬 곱셈(Matrix Multiplication): Python에서 " @"는 행렬 곱셈을 나타내는 기호입니다. 
- tensor @ tensor or torch.mm

In [ ]:
import torch
tensor = torch.tensor([1, 2, 3])


# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
tensor @ tensor

tensor(14)

### 전치 행렬
- 내부 차원 일치시키기 위한 행렬 전치(transpose)
- torch.transpose(input, dim0, dim1) or .T

In [43]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)


In [ ]:
print(tensor_A)
print(tensor_B)

print('------------------------')
# 전치(.T)
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
------------------------
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [48]:
print(torch.matmul(tensor_A, tensor_B.T))

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [ ]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features =2,  # 내부차원 in_features = matches inner dimension of input 
                         out_features =6) # out_features = describes outer value

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


### 집계 함수

In [54]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [56]:
#torch method를 이용 가능 
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### 텐서 데이터 유형 바꾸기
- tensor.type(dtype = None)

In [57]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [58]:
# int8 tensor
tensor_int8 = tensor.type(torch.int8)
print(tensor_int8)

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


### Reshaping, stacking, squeezing and unsqueezing

#### reshaping

In [70]:
# reshaping

a = torch.arange(4.)
print(a)
torch.reshape(a,(2,2))


tensor([0., 1., 2., 3.])


tensor([[0., 1.],
        [2., 3.]])

In [67]:
b= torch.tensor([[0,1],[2,3]])
torch.reshape(b, (-1,))  #단일 차원은 -1일 수 있다. 

tensor([0, 1, 2, 3])

#### view

In [108]:
# view

x= torch.randn(4,4)
x.size()


torch.Size([4, 4])

In [109]:
y = x.view(16)
y.size()

torch.Size([16])

In [110]:
z= x.view(-1,8) # 사이즈 -1은 다른 차원에서 추론한다
print(z)
z.size()

tensor([[-0.3609, -0.0606,  0.0733,  0.8187,  1.4805,  0.3449, -1.4241, -0.1163],
        [ 0.2176, -0.0467, -1.4335, -0.5665, -0.4253,  0.2625, -1.4391,  0.5214]])


torch.Size([2, 8])

In [111]:
a = torch.randn(1,2,3,4)
a.size()

torch.Size([1, 2, 3, 4])

In [112]:
b= a.transpose(1,2) ## Swaps 2nd and 3rd dimension
b.size()

torch.Size([1, 3, 2, 4])

In [113]:
c = a.view(1,3,2,4) # Does not change tensor layout in memory
c.size()             

torch.Size([1, 3, 2, 4])

In [114]:
torch.equal(b,c)

False

#### stack 
- torch.stack(tensors, dim=0, *, out=None) → Tensor

In [115]:
# tensor
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,3])
z = torch.FloatTensor([5,6])

print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 3.],
        [5., 6.]])


#### squeeze

In [116]:
x = torch.zeros(2,1,2,1,2)
x.size()


torch.Size([2, 1, 2, 1, 2])

In [117]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

#### unsqueeze
- torch.unsqueeze(입력,dim)

In [118]:
z = torch.unsqueeze(y,0)
z.size()

torch.Size([1, 2, 2, 2])

#### permute
- torch.permute(input, dims) → Tensor

In [119]:
x = torch.randn(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [120]:
torch.permute(x,(2,0,1)).size() #차원의 순서를 바꾸다 permute = 순열을 만들다

torch.Size([5, 2, 3])

#### 넘파이 판다스 
- torch.from_numpy(ndarray)- NumPy 배열 -> PyTorch 텐서.
- torch.Tensor.numpy()- PyTorch 텐서 -> NumPy 배열.